void csvdat_get_sizes(const char *file_path, int *rows, int *columns);
void csvdat_import(const char *file_path, double * data);
void csvdat_import_cplx(const char *file_path, std::complex<double> *data);
void csvdat_export(const char *file_path, const double *data, int rows, int columns);
void csvdat_export_cplx(const char *file_path, const std::complex<double> *data, int rows, int columns);
void tsvdat_get_sizes(const char *file_path, int *rows, int *columns);
void tsvdat_import(const char *file_path, double * data);
void tsvdat_import_cplx(const char *file_path, std::complex<double> *data);
void tsvdat_export(const char *file_path, const double *data, int rows, int columns);
void tsvdat_export_cplx(const char *file_path, const std::complex<double> *data, int rows, int columns);
int wldat_get_comment_size(const char *file_path);
void wldat_get_comment(const char *file_path, char *comment);
int wldat_get_dimensions(const char *file_path);
void wldat_get_sizes(const char *file_path, int *sizes);
void wldat_import(const char *file_path, double *data);
void wldat_import_cplx(const char *file_path, std::complex<double> *data);
void wldat_export(const char *file_path, double *data, int dimensions, int *sizes, char *comment);
void wldat_export_cplx(const char *file_path, std::complex<double> *data, int dimensions, int *sizes, char *comment);